"""add_professional_table

Revision ID: 1e00d28b454b
Revises: ec99a943b5fe
Create Date: 2023-05-22 13:39:25.441476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e00d28b454b'
down_revision = 'ec99a943b5fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('project', sa.String(length=180), nullable=False))
    op.add_column('professional', sa.Column('responsable', sa.String(length=100), nullable=False))
    op.add_column('professional', sa.Column('work_experience', sa.Integer(), nullable=False))
    op.add_column('professional', sa.Column('level', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('professional', sa.Column('hour_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('professional', sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('professional', sa.Column('current_work', sa.String(length=100), nullable=False))
    op.add_column('professional', sa.Column('to_be_rated', sa.Boolean(), nullable=False))
    op.add_column('professional', sa.Column('data_created', sa.String(length=10), nullable=False))
    op.drop_column('professional', 'data_create')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('data_create', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('professional', 'data_created')
    op.drop_column('professional', 'to_be_rated')
    op.drop_column('professional', 'current_work')
    op.drop_column('professional', 'salary')
    op.drop_column('professional', 'hour_value')
    op.drop_column('professional', 'level')
    op.drop_column('professional', 'work_experience')
    op.drop_column('professional', 'responsable')
    op.drop_column('professional', 'project')
    # ### end Alembic commands ###
